import React from 'react'

const categories = ['تنظيف', 'سباكة', 'كهرباء', 'تجارة', 'تكييف', 'دهانات']
const categoryIcons = ['✦', '⌁', '⚡', '▦', '◒', '◈']
const iconColors = ['bg-[#dff4e9] text-[#087f5b]', 'bg-[#fff0d7] text-[#c5741a]', 'bg-[#e6edff] text-[#4d6ec5]', 'bg-[#f4e4f0] text-[#a3548a]', 'bg-[#e6f2f4] text-[#3c8995]', 'bg-[#f9e5e1] text-[#b75e4d]']
const services = [
  { title: 'تنظيف شامل للمنزل', provider: 'شركة النظافة المتقدمة', price: '150 ر.س', tag: 'الأكثر طلبًا' },
  { title: 'صيانة وتركيب تكييف', provider: 'فريق التبريد المحترف', price: '120 ر.س', tag: 'موصى به' },
  { title: 'إصلاحات كهربائية منزلية', provider: 'كهرباء آمنة', price: '95 ر.س', tag: 'متاح اليوم' },
]
const serviceImage = 'https://lh3.googleusercontent.com/aida-public/AB6AXuCMUFxffyzos393wVhLP4VjQkQcIZcNS8qO8p0wVLZpNATzCmY97rbVnHfpjRB4TVQbklDdjnhNokUIt2sWoxpGiRZHrW4FJwTFApHJqfhbIDIHIY1en0yLeS0i8Zi5j5zLM932rGB66tx1Cr5Via18BNVzxbodZmNeCwe0YcgQXuYbYxmb5zJXfploTi-APx5HWqECbqmnqSioctUbhmldD_3A9TNA9nZloYzRxpgf8n8gilODIGb3'

export default function Home() {
  return <main className="bg-white text-[#132d2a]">
    <section className="overflow-hidden bg-[#eaf7f0]"><div className="mx-auto grid min-h-[560px] w-[calc(100%-32px)] max-w-[1160px] items-center gap-8 md:w-[calc(100%-48px)] md:grid-cols-[1.02fr_.98fr] md:gap-14"><div className="py-12 md:py-14">
      <span className="mb-4 inline-block text-sm font-bold tracking-wide text-[#087f5b]">منصة الخدمات الموثوقة</span><h1 className="mb-6 max-w-[600px] text-[2.6rem] font-bold leading-[1.2] sm:text-5xl md:text-6xl">كل خدمة تحتاجها، <span className="text-[#087f5b]">أقرب مما تتخيل</span></h1>
      <p className="mb-8 max-w-[520px] text-lg leading-8 text-[#647773]">نوصلك بأفضل المتخصصين في مدينتك. ابحث، قارن، واحجز بثقة في دقائق.</p>
      <div className="flex max-w-[570px] items-center rounded-[14px] border border-[#d6e6de] bg-white p-1.5 pl-3 shadow-[0_12px_30px_rgba(34,100,71,0.09)]"><span className="text-2xl text-[#087f5b]" aria-hidden="true">⌕</span><input className="min-w-0 flex-1 border-0 bg-transparent px-2.5 py-3.5 font-[inherit] outline-none" placeholder="ما الخدمة التي تبحث عنها؟" type="text" name="service" /><button className="rounded-[10px] bg-[#087f5b] px-3 py-3 font-bold text-white transition hover:bg-[#056647] sm:px-5" type="button">ابحث الآن</button></div>
      <div className="mt-4 flex flex-wrap items-center gap-2 text-sm text-[#647773]"><span>الأكثر بحثًا:</span><button className="px-1.5 text-[#087f5b] underline underline-offset-4" type="button">تنظيف منازل</button><button className="px-1.5 text-[#087f5b] underline underline-offset-4" type="button">سباكة</button><button className="px-1.5 text-[#087f5b] underline underline-offset-4" type="button">كهرباء</button></div>
    </div><div className="relative flex min-h-[350px] items-center justify-center self-stretch"><div className="absolute h-[300px] w-[300px] rounded-full bg-[#bee8d2] md:h-[430px] md:w-[430px]"></div><div className="relative aspect-[.92] w-[290px] rotate-2 overflow-hidden rounded-[150px_150px_22px_22px] border-8 border-white shadow-[0_25px_45px_rgba(23,96,68,0.18)] md:w-[450px]"><img className="h-full w-full object-cover" src="https://lh3.googleusercontent.com/aida-public/AB6AXuCZ9ry6j2sh0d4THnQsj_wApQw1iEz5n-qsuVWloYb7M4QUn1CRjaC2cw1ybg0_s4NEl5_bozm_lJ3IO4PK9m33043H991jaUVuIIzhfzmlWq9q21YL_gNF0NDZoaVKd3vvlTKdIqtZqBb1UgZTi4O_01iglbJxI_14--dKzhjYezkFSWtV2uLlT8E1z1_Uuzzh_8DaXTdTDUvfpn7apHuBwiG-VcEJ3Me-I9sovsI_7-i_30eoKQWm" alt="متخصص يقدم خدمة منزلية" /></div><div className="absolute bottom-[13%] right-[8%] flex flex-col rounded-xl bg-white px-5 py-3.5 shadow-[0_12px_28px_rgba(23,96,68,0.14)]"><strong className="text-xl text-[#087f5b]">+5,000</strong><span className="text-xs text-[#647773]">متخصص موثوق</span></div></div></div></section>
    <section className="mx-auto w-[calc(100%-32px)] max-w-[1160px] py-16 md:w-[calc(100%-48px)] md:py-[88px]"><div className="mb-8 flex flex-col items-start justify-between gap-5 md:flex-row md:items-end"><div><span className="mb-4 inline-block text-sm font-bold text-[#087f5b]">اكتشف ما يناسبك</span><h2 className="mb-2 text-3xl font-bold">التصنيفات الشائعة</h2><p className="text-[#647773]">اختر من بين خدماتنا الأكثر طلبًا</p></div><button className="font-bold text-[#087f5b]" type="button">عرض كل التصنيفات ←</button></div><div className="grid grid-cols-2 gap-3.5 md:grid-cols-3 lg:grid-cols-6">{categories.map((category, index) => <button className="group flex min-h-[115px] flex-col items-start gap-4 rounded-xl border border-[#e3ebe7] bg-white p-4 text-right transition hover:-translate-y-1 hover:border-[#087f5b] hover:shadow-[0_10px_25px_rgba(23,96,68,0.07)] md:min-h-[130px]" type="button" key={category}><span className={`grid h-11 w-11 place-items-center rounded-[10px] text-xl ${iconColors[index]}`}>{categoryIcons[index]}</span><span>{category}</span><b className="self-end text-[#087f5b]">←</b></button>)}</div></section>
    <section className="bg-[#f6faf8]"><div className="mx-auto w-[calc(100%-32px)] max-w-[1160px] py-16 md:w-[calc(100%-48px)] md:py-[88px]"><div className="mb-8 flex flex-col items-start justify-between gap-5 md:flex-row md:items-end"><div><span className="mb-4 inline-block text-sm font-bold text-[#087f5b]">اختياراتنا لك</span><h2 className="mb-2 text-3xl font-bold">خدمات مميزة</h2><p className="text-[#647773]">خبراء مختارون بعناية لتنفيذ طلبك بأعلى جودة</p></div><button className="w-full rounded-[10px] bg-[#087f5b] px-5 py-3 font-bold text-white transition hover:-translate-y-0.5 hover:bg-[#056647] md:w-auto" type="button">استكشف الخدمات</button></div><div className="grid grid-cols-1 gap-5 md:grid-cols-3">{services.map((service) => <article className="overflow-hidden rounded-[14px] border border-[#e5eee9] bg-white transition hover:-translate-y-1 hover:shadow-[0_16px_35px_rgba(23,96,68,0.08)]" key={service.title}><div className="relative h-[190px] md:h-[210px]"><img className="h-full w-full object-cover" src={serviceImage} alt={service.title} /><span className="absolute right-3.5 top-3.5 rounded-md bg-white px-2.5 py-1.5 text-xs font-bold text-[#087f5b]">{service.tag}</span></div><div className="p-5"><div className="flex items-start justify-between gap-2.5"><h3 className="text-[1.08rem] font-bold">{service.title}</h3><strong className="shrink-0 text-[#087f5b]">{service.price}</strong></div><p className="min-h-[52px] text-sm leading-7 text-[#647773]">خدمة احترافية بجودة عالية ومواد آمنة، مع التزام كامل بالموعد.</p><div className="flex items-center gap-2 border-t border-[#edf2ef] pt-4"><span className="grid h-8 w-8 place-items-center rounded-full bg-[#dff4e9] font-bold text-[#087f5b]">{service.provider.charAt(0)}</span><span className="flex flex-col gap-0.5"><small className="text-[.7rem] text-[#91a19d]">بواسطة</small><b className="text-xs">{service.provider}</b></span><span className="mr-auto text-sm text-[#bd7a19]">★ 4.9</span></div></div></article>)}</div></div></section>
    <section className="mx-auto w-[calc(100%-32px)] max-w-[1160px] pb-20 pt-16 md:w-[calc(100%-48px)] md:pb-[105px] md:pt-[88px]"><div className="mb-8 text-center"><span className="mb-4 inline-block text-sm font-bold text-[#087f5b]">بكل بساطة</span><h2 className="mb-2 text-3xl font-bold">كيف تعمل خدمة؟</h2><p className="text-[#647773]">ثلاث خطوات تفصلك عن الخدمة التي تريدها</p></div><div className="grid grid-cols-1 gap-7 md:grid-cols-3 md:gap-12">{[['01', 'ابحث عن الخدمة', 'تصفح الخيارات واختر الخدمة التي تناسب احتياجاتك.'], ['02', 'حدد الموعد', 'اختر الوقت المناسب لك وتابع تفاصيل الحجز بسهولة.'], ['03', 'استمتع بالنتيجة', 'سيصلك المتخصص لإنجاز العمل باحترافية وأمان.']].map(([number, title, description]) => <div className="text-center" key={number}><span className="mx-auto mb-4 grid h-14 w-14 place-items-center rounded-full bg-[#dff4e9] font-bold text-[#087f5b]">{number}</span><h3 className="mb-2 font-bold">{title}</h3><p className="leading-7 text-[#647773]">{description}</p></div>)}</div></section>
  </main>
}
